### ISSUE TITLE
Typescript types declaration

### ISSUE THREAD

**Issue by dgellow** [Skayo/svelte-infinite-loading#1]
Hey there. In case you're interested, I created a small declaration file for Typescript types for this library for my own use.

```ts
declare module "svelte-infinite-loading" {
	export interface InfiniteLoadingProps {
		distance?: number
		spinner?: "default" | "spiral" | "circles" | "bubbles" | "wavedots"
		direction?: "top" | "bottom"
		forceUseInfiniteWrapper?: boolean | string
		identifier?: any
	}

	export default class {
		$$prop_def: InfiniteLoadingProps
	}
}
```

If you add it to the files shipped to npm that would allow typescript users to get type information.
I'm just sharing it here in case that might interest you, but feel free to close this issue if you don't care :)

Cheers!

**Comment by Skayo** [comment]
@dgellow 
I've added the type declarations now! Thanks for your help.  
Let me know if something doesn't work.

**Comment by dgellow** [comment]
Awesome, thank you :)
