### ISSUE TITLE
Is there any way to remove no more data message?

### ISSUE THREAD

**Issue by limjunhyuk97** [skayo/svelte-infinite-loading#11]
Hi, I'm currently using your work for shopping mall project. 
And, I noticed that there is no given documents for customizing"no more data" message. 
So I leaved an issue to ask you about some ways to customize those messages. 

Thank you.

**Comment by skayo** [comment]
You can remove the message like this:
```
<InfiniteLoading>
  <span slot="noMore"></span>
</InfiniteLoading>
```
The same works for all the other slots (`noResults`, `error`, `spinner`)

In the future I will probably make it empty by default....

**Comment by limjunhyuk97** [comment]
Thanks a lot! This really helps me ;)
