### ISSUE TITLE
window.remove vs window.removeEventListener in third argument detection.

### ISSUE THREAD

**Issue by whataboutpereira** [Skayo/svelte-infinite-loading#5]
https://github.com/Skayo/svelte-infinite-loading/blob/86b3f25adcf4c3c27ab06483b9ae5b1eea1668ed/src/InfiniteLoading.svelte#L39-L40

I looked at the referenced EventListenerOptions doc and suspect `window.remove` should be `window.removeEventListener` here?

**Comment by Skayo** [comment]
Yes! You're right. Will fix that...
